import {useEffect,useState} from 'react';
import {supabase,editorEmail} from '@/lib/supabase';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
export function EditorAccess({onAccessChange}:{onAccessChange:(allowed:boolean)=>void}){
 const [allowed,setAllowed]=useState(false),[open,setOpen]=useState(false),[email,setEmail]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 useEffect(()=>{let active=true;const check=async()=>{const {data:{user}}=await supabase.auth.getUser();if(!active)return;const ok=!!user?.email_confirmed_at&&user?.email?.toLowerCase()===editorEmail;setAllowed(ok);onAccessChange(ok)};void check();const {data:{subscription}}=supabase.auth.onAuthStateChange(()=>{setTimeout(()=>{void check()},0)});return()=>{active=false;subscription.unsubscribe()}},[onAccessChange]);
 async function login(){if(email.trim().toLowerCase()!==editorEmail){setNotice('Este correo no está autorizado para editar el tablero.');return}setBusy(true);setNotice('');try{const {error}=await supabase.auth.signInWithOtp({email:email.trim().toLowerCase(),options:{emailRedirectTo:new URL('.',window.location.href).href}});setNotice(error?'No se pudo enviar el enlace. Revisa la configuración de correo de Supabase o inténtalo más tarde.':'Revisa tu correo y abre el enlace para ingresar. También revisa la carpeta de spam.')}catch{setNotice('No se pudo conectar. Intenta nuevamente.')}finally{setBusy(false)}}
 async function logout(){const {error}=await supabase.auth.signOut();if(error){setNotice('No se pudo cerrar la sesión. Intenta nuevamente.');setOpen(true);return}setAllowed(false);onAccessChange(false)}
 return <><div className="access-bar"><span>{allowed?'Sesión de edición activa':'Consulta pública · edición con acceso autorizado'}</span><Button variant="outline" onClick={()=>allowed?void logout():setOpen(true)}>{allowed?'Cerrar sesión':'Ingresar para editar'}</Button></div><Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogTitle>Acceso para editar</DialogTitle><DialogDescription>Recibe un enlace de acceso en el correo autorizado. No necesitas contraseña.</DialogDescription><label>Correo<input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><Button disabled={busy} onClick={login}>{busy?'Enviando…':'Enviar enlace de acceso'}</Button>{notice&&<p role="status">{notice}</p>}</DialogContent></Dialog></>
}
